# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(max_length=250, upload_to=''),
        ),
    ]
